camunda:
  bpm:
    admin-user:
      id: kermit
      password: superSecret
      first-name: kermit
    filter:
      create: All tasks
    database:
      type: mysql

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.101:3306/camunda?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
